-- CreateEnum
CREATE TYPE "ConstructionType" AS ENUM ('FIBERGLASS', 'CONCRETE', 'BLOCKS', 'PANELS');

-- AlterTable
ALTER TABLE "CalculationSettings" ADD COLUMN     "bedCementBagWeight" DOUBLE PRECISION NOT NULL DEFAULT 50.0,
ADD COLUMN     "bedCementBagsPerM3" DOUBLE PRECISION NOT NULL DEFAULT 5.0,
ADD COLUMN     "bedThicknessCm" DOUBLE PRECISION NOT NULL DEFAULT 10.0,
ADD COLUMN     "drainTrenchDepthCm" DOUBLE PRECISION NOT NULL DEFAULT 15.0,
ADD COLUMN     "drainTrenchWidthCm" DOUBLE PRECISION NOT NULL DEFAULT 15.0,
ADD COLUMN     "electroweldedMeshM2PerM2" DOUBLE PRECISION NOT NULL DEFAULT 1.15,
ADD COLUMN     "geomembraneM2PerM2" DOUBLE PRECISION NOT NULL DEFAULT 1.0;

-- AlterTable
ALTER TABLE "PoolPreset" ADD COLUMN     "constructionType" "ConstructionType" NOT NULL DEFAULT 'FIBERGLASS';
